#!/bin/zsh

REQUIRED_VERSION='0.51.2'

if ! type swiftformat > /dev/null; then
  echo "swiftformat not installed"
  exit 1
fi

CURRENT_VERSION=$(swiftformat --version)

if [ $CURRENT_VERSION != $REQUIRED_VERSION ]; then
  echo "swiftformat required version $REQUIRED_VERSION, current version $CURRENT_VERSION"
  exit 1
else
  swiftformat $1
fi
