name: Code linting/formatting

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      
      - name: Lint code using SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1
        with:
          args: --strict
  
  SwiftFormat:
    name: SwiftFormat
    runs-on: macos-12
    timeout-minutes: 5
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Run SwiftFormat
        run: ./scripts/swiftformat
